---
- hosts: localhost
  connection: local
  user: ghken
  vars:
      ghken_home: "/home/ghken"
  tasks:
    - name: install packages
      apt: name={{item}} update_cache=yes
      with_items:
          - zsh
          - git
          - tig
          - vim
          - tmux
          - language-pack-ja
      become: yes
    - name: clone personal settings
      git: repo=https://github.com/GHKEN/dotfiles.git
           dest={{ghken_home}}/dotfiles
    - name: simlink zshrc
      file: src={{ghken_home}}/dotfiles/.zshrc dest={{ghken_home}}/.zshrc state=link
    - name: simlink gitconfig
      file: src={{ghken_home}}/dotfiles/.gitconfig dest={{ghken_home}}/.gitconfig state=link
    - name: change shell
      user: name=ghken shell=/usr/bin/zsh
      become: yes
