---
- hosts: vagrants
  user: vagrant
  vars:
      vagrant_home: "/home/vagrant"
  tasks:
    - name: install packages
      apt: name={{item}} update_cache=yes
      with_items:
          - zsh
          - git
          - tig
          - vim
          - tmux
          - language-pack-ja
      become: yes
    - name: clone personal settings
      git: repo=https://github.com/GHKEN/dotfiles.git
           dest={{vagrant_home}}/dotfiles
    - name: simlink conf
      file: src={{vagrant_home}}/dotfiles/{{item}} dest={{vagrant_home}}/{{item}} state=link
      with_items:
          - .zshrc
          - .tigrc
          - .tmux.conf
          - .vim
          - .vimrc
    - name: change shell
      user: name=vagrant shell=/usr/bin/zsh
      become: yes
