---
- hosts: localhost
  connection: local
  become: yes
  user: ghken
  vars:
      ghken_home: "/home/ghken"
  tasks:
    - name: create user
      user: name=ghken uid=1001
    - name: create .ssh
      file: dest=/home/ghken/.ssh/ state=directory owner=ghken group=ghken mode=700
    - name: copy authorized_key
      copy: src=/home/ubuntu/.ssh/authorized_keys dest=/home/ghken/.ssh/authorized_keys owner=ghken group=ghken mode=700
    - name: install packages
      apt: name={{item}} update_cache=yes
      with_items:
          - zsh
          - git
          - tig
          - vim
          - tmux
          - language-pack-ja
      become: yes
    - name: clone personal settings
      git: repo=https://github.com/GHKEN/dotfiles.git
           dest={{ghken_home}}/dotfiles
    - name: simlink conf
      file: src={{ghken_home}}/dotfiles/{{item}} dest={{ghken_home}}/{{item}} state=link
      with_items:
          - .zshrc
          - .tigrc
          - .tmux.conf
          - .vim
          - .vimrc
    - name: change shell
      user: name=ghken shell=/usr/bin/zsh
      become: yes
    - name: add sudoer
      lineinfile:
        dest: /etc/sudoers
        backup: yes
        line: 'ghken ALL=(ALL) NOPASSWD: ALL'
